"""add tables

Revision ID: 0f01f5302d96
Revises:
Create Date: 2025-11-30 21:46:23.881407

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f01f5302d96"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discount_types",
        sa.Column("discount_type_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("discount_type_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "districts",
        sa.Column("district_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("district_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "employees",
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("birth_date", sa.DateTime(), nullable=True),
        sa.Column("employment_date", sa.DateTime(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("login", sa.String(length=50), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("employee_id"),
    )
    op.create_table(
        "roles",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("role_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "subscription_statuses",
        sa.Column("subscription_status_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("subscription_status_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tariff_types",
        sa.Column("tariff_type_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("tariff_type_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tariff_validity_periods",
        sa.Column("tariff_validity_period_id", sa.UUID(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tariff_validity_period_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("birth_date", sa.DateTime(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("login", sa.String(length=50), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "branches",
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("contacts", sa.String(), nullable=True),
        sa.Column("operating_hours", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("district_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.district_id"],
        ),
        sa.PrimaryKeyConstraint("branch_id"),
    )
    op.create_table(
        "employee_roles",
        sa.Column("employee_role_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"], ["employees.employee_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.role_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("employee_role_id"),
    )
    op.create_table(
        "promotions",
        sa.Column("promotion_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("starts_at", sa.Date(), nullable=False),
        sa.Column("ends_at", sa.Date(), nullable=False),
        sa.Column("discount_value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("discount_type_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["discount_type_id"],
            ["discount_types.discount_type_id"],
        ),
        sa.PrimaryKeyConstraint("promotion_id"),
    )
    op.create_table(
        "tariffs",
        sa.Column("tariff_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("tariff_type_id", sa.UUID(), nullable=False),
        sa.Column("tariff_validity_period_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tariff_type_id"],
            ["tariff_types.tariff_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tariff_validity_period_id"],
            ["tariff_validity_periods.tariff_validity_period_id"],
        ),
        sa.PrimaryKeyConstraint("tariff_id"),
    )
    op.create_table(
        "employee_branches",
        sa.Column("employee_branch_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.branch_id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.employee_id"],
        ),
        sa.PrimaryKeyConstraint("employee_branch_id"),
    )
    op.create_table(
        "promotion_branches",
        sa.Column("promotion_branch_id", sa.UUID(), nullable=False),
        sa.Column("promotion_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.branch_id"],
        ),
        sa.ForeignKeyConstraint(
            ["promotion_id"],
            ["promotions.promotion_id"],
        ),
        sa.PrimaryKeyConstraint("promotion_branch_id"),
    )
    op.create_table(
        "promotion_tariffs",
        sa.Column("promotion_tariff_id", sa.UUID(), nullable=False),
        sa.Column("promotion_id", sa.UUID(), nullable=False),
        sa.Column("tariff_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["promotion_id"],
            ["promotions.promotion_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tariff_id"],
            ["tariffs.tariff_id"],
        ),
        sa.PrimaryKeyConstraint("promotion_tariff_id"),
    )
    op.create_table(
        "subscriptions",
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("tariff_id", sa.UUID(), nullable=False),
        sa.Column("subscription_status_id", sa.UUID(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.branch_id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_status_id"],
            ["subscription_statuses.subscription_status_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tariff_id"],
            ["tariffs.tariff_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("subscription_id"),
    )
    op.create_table(
        "visits",
        sa.Column("visit_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("entered_at", sa.DateTime(), nullable=False),
        sa.Column("exited_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.branch_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("visit_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("visits")
    op.drop_table("subscriptions")
    op.drop_table("promotion_tariffs")
    op.drop_table("promotion_branches")
    op.drop_table("employee_branches")
    op.drop_table("tariffs")
    op.drop_table("promotions")
    op.drop_table("employee_roles")
    op.drop_table("branches")
    op.drop_table("users")
    op.drop_table("tariff_validity_periods")
    op.drop_table("tariff_types")
    op.drop_table("subscription_statuses")
    op.drop_table("roles")
    op.drop_table("employees")
    op.drop_table("districts")
    op.drop_table("discount_types")
    # ### end Alembic commands ###
